services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    restart: always
    networks:
      - frontend
    ports:
      - 3000:3000
    environment:
      DOMAIN_URL: "${DOMAIN_URL}"
    volumes:
      - /app/node_modules
      - ./frontend:/app

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    networks:
      - frontend
      - backend
    ports:
      - 4000:4000
    volumes:
      - type: bind
        target: /pixil-media/
        source: /home/span/Pictures/pixil/
    depends_on:
      - postgres
    develop:
      watch:
        - action: rebuild
          path: ./backend/

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  pg_data:
